# Generated by Django 2.1.7 on 2019-03-26 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artige_id', models.IntegerField()),
                ('title', models.CharField(max_length=12000)),
                ('description', models.CharField(max_length=12000)),
                ('tags', models.CharField(max_length=12000)),
                ('images', models.CharField(max_length=12000)),
                ('post_like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=512)),
                ('post', models.ManyToManyField(to='WebUI.Post')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liker', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('post', models.ManyToManyField(to='WebUI.Post')),
            ],
        ),
    ]
